# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99725183202062d7e71d5851bbcfe7670be611bdee945986e9576cd5f58eb2a7c2636e59949e3eb151a3a9a1729b1d5433c458e92c7e45d563c251c640733b8

test:
  secret_key_base: 2c38bfa43463e014e495dd2ccc38a22bb9cd423c84cc3e1ed4e6bd2fd2e6eb03c1f09e33a36bbf4bb908663e02db01509d7f593a78bb73b6eb9957300148e7d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
